version: "3.7"

services:
  excalidraw-alternative-store:
    image: ghcr.io/cocreators-ee/excalidraw-alternative-store
    restart: unless-stopped
    environment:
      PORT: 80
      OVERRIDE_PROTOCOL: https
      CORS_ALLOW_ORIGINS: https://${APP_HOST}
    volumes:
      - ./storage:/src/storage
    networks:
      - coolify
    labels:
      - traefik.enable=true
      - traefik.docker.network=coolify
  app:
    image: alswl/excalidraw:v0.17.3-fork-b1
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
    environment:
      - VITE_APP_BACKEND_V2_GET_URL=https://${STORAGE_BACKEND_HOST}/api/v2/scenes/
      - VITE_APP_BACKEND_V2_POST_URL=https://${STORAGE_BACKEND_HOST}/api/v2/scenes/
      - VITE_APP_WS_SERVER_URL=https://${ROOM_HOST}/
      - VITE_APP_FIREBASE_CONFIG={}
      - VITE_APP_HTTP_STORAGE_BACKEND_URL=https://${STORAGE_BACKEND_HOST}/api/v2
      - VITE_APP_STORAGE_BACKEND=http
      - VITE_APP_DISABLE_TRACKING=true
      - PUBLIC_URL=https://${APP_HOST}
    networks:
      - coolify
    labels:
      - traefik.enable=true
      - traefik.docker.network=coolify

  storage:
    image: alswl/excalidraw-storage-backend:v2023.11.11
    restart: unless-stopped
    environment:
      - STORAGE_URI=mongodb://${DB_USER}:${DB_PASS}@mongodb:27017
    networks:
      - coolify
      - draw-internal
    labels:
      - traefik.enable=true
      - traefik.docker.network=coolify

  room:
    image: excalidraw/excalidraw-room:sha-49bf529
    restart: unless-stopped
    networks:
      - coolify 
    labels:
      - traefik.enable=true
      - traefik.docker.network=coolify

  mongodb:
    image: mongo:7.0.5-jammy
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASS}
    volumes:
      - ${DB_VOLUME_PATH}:/data/db
    networks:
      - draw-internal
    labels:
      - "traefik.enable=false"

  mongoexpress:
    image: mongo-express:latest
    environment:
      - ME_CONFIG_MONGODB_URL=mongodb://${DB_USER}:${DB_PASS}@mongodb:27017
      - ME_CONFIG_BASICAUTH=true
      - ME_CONFIG_BASICAUTH_USERNAME=${MONGOEXPRESS_USER}
      - ME_CONFIG_BASICAUTH_PASSWORD=${MONGOEXPRESS_PASS}
    depends_on:
      - mongodb
    restart: unless-stopped
    networks:
      - coolify
      - draw-internal
    labels:
      - traefik.enable=true
      - traefik.docker.network=coolify
      
networks:
  coolify:
    external: true
  draw-internal:
    external: false
  zsgwgwcgk8co0ss88ow880oc:
    external: true
